### 2.3.5 Sequences and Slice Notation



In [6]:
import numpy as np
#np.linspace?

In [7]:
seq1 = np.linspace(0, 10, 11) #從 0 開始，10 結束，長度 10
seq1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
seq2 = np.arange(0, 10)
seq2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
"hello world"[3:6]

'lo '

In [10]:
"hello world"[slice(3,6)]

'lo '

In [11]:
seq2[3:6] 

array([3, 4, 5])

### 2.3.6 Indexing Data

In [12]:
A = np.array(np.arange(16)).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
#?np.arange

In [14]:
A[1,2]

6

#### Indexing Rows, Columns, and Submatrices

In [15]:
A[1] #選出第2個 raw

array([4, 5, 6, 7])

In [16]:
A[[1,3]] #選出 [1,3] 兩個 raw

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [17]:
A[:,[0,2]] # 選出第 1, 3 個 column

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [18]:
np.array([A[1,0],A[3,2]])

array([ 4, 14])

In [19]:
A[[1,3],[0,2]] #等同於 np.array([A[1,0],A[3,2]])

array([ 4, 14])

In [20]:
A[[1,3],[0,2,3]] #兩個 list 長度要一樣

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [21]:
A[[1,3]][:,[0,2,3]] #先取 2,4 rows, 再取 1,3 column

array([[ 4,  6,  7],
       [12, 14, 15]])

In [22]:
idx = np.ix_([1,3],[0,2,3])
A[idx]

array([[ 4,  6,  7],
       [12, 14, 15]])

In [23]:
print(A)
A[1:4:2 ,0:3:2] # 1:4:2 (slice) 代表 (start:end:間格)，所以是第 1+1 和第 3+1 row; 0:3:2 為 column 0+1,2+1  

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 4,  6],
       [12, 14]])

#### Boolean (布林) Indexing

Boolean: True or False, 

In [24]:
keep_rows = np.zeros(A.shape[0], bool) # A.shape[0]: array A 的 row 數目,  0 = False 
keep_rows

array([False, False, False, False])

In [25]:
keep_rows[[1,3]] = True #令第2,4 位置為 TRUE
keep_rows

array([False,  True, False,  True])

In [26]:
np.all(keep_rows == np.array([0,1,0,1])) #檢查 array 的元素是否都是 True

True

In [27]:
A[np.array([0,1,0,1])]

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [28]:
A[keep_rows]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [29]:
keep_cols = np.zeros(A.shape[1], bool)
keep_cols[[0, 2, 3]] = True
idx_bool = np.ix_(keep_rows , keep_cols) # ix_():對目標 array 選取需要的資料, keep_raw: 1,3; keep_col: 0,2,3
A[idx_bool]

array([[ 4,  6,  7],
       [12, 14, 15]])

In [30]:
idx_mixed = np.ix_([1,3], keep_cols) #ix_()裡面可以放 list or Booleans

### 2.3.7 Loading Data

*data frame*: 資料矩陣，裡面可以包含不同型態的資料，如數值、文字等
*pandas*: 在這裡使用 pandas ibrary 來讀取資料

#### Reading in a Data Set

系統預設的讀檔位置為 notebook 檔案所在位置，若要改變位置，使用:

*os.chdir*: 改變讀檔位置，需要先引入 os library (*import os*)


In [33]:
import os
os.getcwd()


'C:\\Users\\user\\LHChien'

In [37]:
os.chdir("C:\\Users\\user\\Documents\\LHChien\\Python\\data") #C:\Users\User\Documents\Python Scripts\data

In [38]:
import pandas as pd
Auto = pd.read_csv('Auto.csv') #.csv: 用逗號分隔
Auto

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70   
1    15.0          8         350.0        165    3693          11.5    70   
2    18.0          8         318.0        150    3436          11.0    70   
3    16.0          8         304.0        150    3433          12.0    70   
4    17.0          8         302.0        140    3449          10.5    70   
..    ...        ...           ...        ...     ...           ...   ...   
392  27.0          4         140.0         86    2790          15.6    82   
393  44.0          4          97.0         52    2130          24.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin                       name  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
392       1            ford mustang gl  
393       2                  vw pickup  
394       1              dodge rampage  
395       1                ford ranger  
396       1                 chevy s-10  

[397 rows x 9 columns]

In [39]:
Auto = pd.read_csv('Auto.data', delim_whitespace=True) # delim_whitespace: 用空白分隔

In [40]:
Auto['horsepower']

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...  
392    86.00
393    52.00
394    84.00
395    79.00
396    82.00
Name: horsepower, Length: 397, dtype: object

dtype: object 代表 horsepower 的資料格式為字串 (string)

In [41]:
np.unique(Auto['horsepower']) # 列出陣列中所有不同的元素: 發現有"?" 因此在讀資料的時候，horsepower被定為string

array(['100.0', '102.0', '103.0', '105.0', '107.0', '108.0', '110.0',
       '112.0', '113.0', '115.0', '116.0', '120.0', '122.0', '125.0',
       '129.0', '130.0', '132.0', '133.0', '135.0', '137.0', '138.0',
       '139.0', '140.0', '142.0', '145.0', '148.0', '149.0', '150.0',
       '152.0', '153.0', '155.0', '158.0', '160.0', '165.0', '167.0',
       '170.0', '175.0', '180.0', '190.0', '193.0', '198.0', '200.0',
       '208.0', '210.0', '215.0', '220.0', '225.0', '230.0', '46.00',
       '48.00', '49.00', '52.00', '53.00', '54.00', '58.00', '60.00',
       '61.00', '62.00', '63.00', '64.00', '65.00', '66.00', '67.00',
       '68.00', '69.00', '70.00', '71.00', '72.00', '74.00', '75.00',
       '76.00', '77.00', '78.00', '79.00', '80.00', '81.00', '82.00',
       '83.00', '84.00', '85.00', '86.00', '87.00', '88.00', '89.00',
       '90.00', '91.00', '92.00', '93.00', '94.00', '95.00', '96.00',
       '97.00', '98.00', '?'], dtype=object)

In [42]:
Auto = pd.read_csv('Auto.data',
                    na_values=['?'],  # 將 "?" 視為 missing (na)
                    delim_whitespace=True)
Auto['horsepower'].sum()

40952.0

In [43]:
Auto.shape #資料大小: 共 397樣本，9變數

(397, 9)

In [44]:
Auto_new = Auto.dropna() #把有 missing 的樣本去掉
Auto_new.shape #去掉 missing 後，樣本數為 392(去掉五個樣本)

(392, 9)

#### Basics of Selecting Rows and Columns

In [45]:
Auto = Auto_new # overwrite the previous value
Auto.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name'],
      dtype='object')

In [46]:
Auto[:3] #列出前三筆樣本資料 (0,1,2)

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0       130.0  3504.0          12.0    70   
1  15.0          8         350.0       165.0  3693.0          11.5    70   
2  18.0          8         318.0       150.0  3436.0          11.0    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite

In [47]:
idx_80 = Auto['year'] > 80 #TRUE FALSE 變數，year >80 的樣本為 TRUE
Auto[idx_80]

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
338  27.2          4         135.0        84.0  2490.0          15.7    81   
339  26.6          4         151.0        84.0  2635.0          16.4    81   
340  25.8          4         156.0        92.0  2620.0          14.4    81   
341  23.5          6         173.0       110.0  2725.0          12.6    81   
342  30.0          4         135.0        84.0  2385.0          12.9    81   
343  39.1          4          79.0        58.0  1755.0          16.9    81   
344  39.0          4          86.0        64.0  1875.0          16.4    81   
345  35.1          4          81.0        60.0  1760.0          16.1    81   
346  32.3          4          97.0        67.0  2065.0          17.8    81   
347  37.0          4          85.0        65.0  1975.0          19.4    81   
348  37.7          4          89.0        62.0  2050.0          17.3    81   
349  34.1          4          91.0        68.0  1985.0          16.0    81   
350  34.7          4         105.0        63.0  2215.0          14.9    81   
351  34.4          4          98.0        65.0  2045.0          16.2    81   
352  29.9          4          98.0        65.0  2380.0          20.7    81   
353  33.0          4         105.0        74.0  2190.0          14.2    81   
355  33.7          4         107.0        75.0  2210.0          14.4    81   
356  32.4          4         108.0        75.0  2350.0          16.8    81   
357  32.9          4         119.0       100.0  2615.0          14.8    81   
358  31.6          4         120.0        74.0  2635.0          18.3    81   
359  28.1          4         141.0        80.0  3230.0          20.4    81   
360  30.7          6         145.0        76.0  3160.0          19.6    81   
361  25.4          6         168.0       116.0  2900.0          12.6    81   
362  24.2          6         146.0       120.0  2930.0          13.8    81   
363  22.4          6         231.0       110.0  3415.0          15.8    81   
364  26.6          8         350.0       105.0  3725.0          19.0    81   
365  20.2          6         200.0        88.0  3060.0          17.1    81   
366  17.6          6         225.0        85.0  3465.0          16.6    81   
367  28.0          4         112.0        88.0  2605.0          19.6    82   
368  27.0          4         112.0        88.0  2640.0          18.6    82   
369  34.0          4         112.0        88.0  2395.0          18.0    82   
370  31.0          4         112.0        85.0  2575.0          16.2    82   
371  29.0          4         135.0        84.0  2525.0          16.0    82   
372  27.0          4         151.0        90.0  2735.0          18.0    82   
373  24.0          4         140.0        92.0  2865.0          16.4    82   
374  36.0          4         105.0        74.0  1980.0          15.3    82   
375  37.0          4          91.0        68.0  2025.0          18.2    82   
376  31.0          4          91.0        68.0  1970.0          17.6    82   
377  38.0          4         105.0        63.0  2125.0          14.7    82   
378  36.0          4          98.0        70.0  2125.0          17.3    82   
379  36.0          4         120.0        88.0  2160.0          14.5    82   
380  36.0          4         107.0        75.0  2205.0          14.5    82   
381  34.0          4         108.0        70.0  2245.0          16.9    82   
382  38.0          4          91.0        67.0  1965.0          15.0    82   
383  32.0          4          91.0        67.0  1965.0          15.7    82   
384  38.0          4          91.0        67.0  1995.0          16.2    82   
385  25.0          6         181.0       110.0  2945.0          16.4    82   
386  38.0          6         262.0        85.0  3015.0          17.0    82   
387  26.0          4         156.0        92.0  2585.0          14.5    82   
388  22.0          6         232.0       112.0  2835.0          14.7    82   
389  32.0          4        

In [48]:
Auto_re = Auto.set_index('name') #將 index 的名稱改成 name 變數內容
Auto_re

mpg  cylinders  displacement  horsepower  weight  \
name                                                                           
chevrolet chevelle malibu  18.0          8         307.0       130.0  3504.0   
buick skylark 320          15.0          8         350.0       165.0  3693.0   
plymouth satellite         18.0          8         318.0       150.0  3436.0   
amc rebel sst              16.0          8         304.0       150.0  3433.0   
ford torino                17.0          8         302.0       140.0  3449.0   
...                         ...        ...           ...         ...     ...   
ford mustang gl            27.0          4         140.0        86.0  2790.0   
vw pickup                  44.0          4          97.0        52.0  2130.0   
dodge rampage              32.0          4         135.0        84.0  2295.0   
ford ranger                28.0          4         120.0        79.0  2625.0   
chevy s-10                 31.0          4         119.0        82.0  2720.0   

                           acceleration  year  origin  
name                                                   
chevrolet chevelle malibu          12.0    70       1  
buick skylark 320                  11.5    70       1  
plymouth satellite                 11.0    70       1  
amc rebel sst                      12.0    70       1  
ford torino                        10.5    70       1  
...                                 ...   ...     ...  
ford mustang gl                    15.6    82       1  
vw pickup                          24.6    82       2  
dodge rampage                      11.6    82       1  
ford ranger                        18.6    82       1  
chevy s-10                         19.4    82       1  

[392 rows x 8 columns]

In [49]:
Auto_re.columns #將 index 設成 name 變數時，name變數也不見了

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin'],
      dtype='object')

In [50]:
rows = ['amc rebel sst', 'ford torino']
Auto_re.loc[rows] #也可以用 index 名稱來選取樣本

mpg  cylinders  displacement  horsepower  weight  \
name                                                               
amc rebel sst  16.0          8         304.0       150.0  3433.0   
ford torino    17.0          8         302.0       140.0  3449.0   

               acceleration  year  origin  
name                                       
amc rebel sst          12.0    70       1  
ford torino            10.5    70       1

In [51]:
Auto_re.iloc[[3,4]] #用list 選

mpg  cylinders  displacement  horsepower  weight  \
name                                                               
amc rebel sst  16.0          8         304.0       150.0  3433.0   
ford torino    17.0          8         302.0       140.0  3449.0   

               acceleration  year  origin  
name                                       
amc rebel sst          12.0    70       1  
ford torino            10.5    70       1

In [52]:
Auto_re.iloc[:,[0,2,3]]

mpg  displacement  horsepower
name                                                     
chevrolet chevelle malibu  18.0         307.0       130.0
buick skylark 320          15.0         350.0       165.0
plymouth satellite         18.0         318.0       150.0
amc rebel sst              16.0         304.0       150.0
ford torino                17.0         302.0       140.0
...                         ...           ...         ...
ford mustang gl            27.0         140.0        86.0
vw pickup                  44.0          97.0        52.0
dodge rampage              32.0         135.0        84.0
ford ranger                28.0         120.0        79.0
chevy s-10                 31.0         119.0        82.0

[392 rows x 3 columns]

In [53]:
Auto_re.iloc[[3,4],[0,2,3]]

mpg  displacement  horsepower
name                                         
amc rebel sst  16.0         304.0       150.0
ford torino    17.0         302.0       140.0

In [54]:
Auto_re.loc['ford galaxie 500', ['mpg', 'origin']] #index 的名稱可以重複，index為ford galaxie 500 的資料共有三筆

mpg  origin
name                          
ford galaxie 500  15.0       1
ford galaxie 500  14.0       1
ford galaxie 500  14.0       1

#### More on Selecting Rows and Columns


In [55]:
idx_80 = Auto_re['year'] > 81
Auto_re.loc[idx_80 , ['weight', 'origin']]

weight  origin
name                                             
chevrolet cavalier                 2605.0       1
chevrolet cavalier wagon           2640.0       1
chevrolet cavalier 2-door          2395.0       1
pontiac j2000 se hatchback         2575.0       1
dodge aries se                     2525.0       1
pontiac phoenix                    2735.0       1
ford fairmont futura               2865.0       1
volkswagen rabbit l                1980.0       2
mazda glc custom l                 2025.0       3
mazda glc custom                   1970.0       3
plymouth horizon miser             2125.0       1
mercury lynx l                     2125.0       1
nissan stanza xe                   2160.0       3
honda accord                       2205.0       3
toyota corolla                     2245.0       3
honda civic                        1965.0       3
honda civic (auto)                 1965.0       3
datsun 310 gx                      1995.0       3
buick century limited              2945.0       1
oldsmobile cutlass ciera (diesel)  3015.0       1
chrysler lebaron medallion         2585.0       1
ford granada l                     2835.0       1
toyota celica gt                   2665.0       3
dodge charger 2.2                  2370.0       1
chevrolet camaro                   2950.0       1
ford mustang gl                    2790.0       1
vw pickup                          2130.0       2
dodge rampage                      2295.0       1
ford ranger                        2625.0       1
chevy s-10                         2720.0       1

In [56]:
Auto_re.loc[lambda df: df['year'] > 81, ['weight', 'origin']] #function lambda: df 為 argument

weight  origin
name                                             
chevrolet cavalier                 2605.0       1
chevrolet cavalier wagon           2640.0       1
chevrolet cavalier 2-door          2395.0       1
pontiac j2000 se hatchback         2575.0       1
dodge aries se                     2525.0       1
pontiac phoenix                    2735.0       1
ford fairmont futura               2865.0       1
volkswagen rabbit l                1980.0       2
mazda glc custom l                 2025.0       3
mazda glc custom                   1970.0       3
plymouth horizon miser             2125.0       1
mercury lynx l                     2125.0       1
nissan stanza xe                   2160.0       3
honda accord                       2205.0       3
toyota corolla                     2245.0       3
honda civic                        1965.0       3
honda civic (auto)                 1965.0       3
datsun 310 gx                      1995.0       3
buick century limited              2945.0       1
oldsmobile cutlass ciera (diesel)  3015.0       1
chrysler lebaron medallion         2585.0       1
ford granada l                     2835.0       1
toyota celica gt                   2665.0       3
dodge charger 2.2                  2370.0       1
chevrolet camaro                   2950.0       1
ford mustang gl                    2790.0       1
vw pickup                          2130.0       2
dodge rampage                      2295.0       1
ford ranger                        2625.0       1
chevy s-10                         2720.0       1

In [57]:
Auto_re.loc[lambda df: (df['year'] > 81) & (df['mpg'] > 30),['weight', 'origin']]

weight  origin
name                                             
chevrolet cavalier 2-door          2395.0       1
pontiac j2000 se hatchback         2575.0       1
volkswagen rabbit l                1980.0       2
mazda glc custom l                 2025.0       3
mazda glc custom                   1970.0       3
plymouth horizon miser             2125.0       1
mercury lynx l                     2125.0       1
nissan stanza xe                   2160.0       3
honda accord                       2205.0       3
toyota corolla                     2245.0       3
honda civic                        1965.0       3
honda civic (auto)                 1965.0       3
datsun 310 gx                      1995.0       3
oldsmobile cutlass ciera (diesel)  3015.0       1
toyota celica gt                   2665.0       3
dodge charger 2.2                  2370.0       1
vw pickup                          2130.0       2
dodge rampage                      2295.0       1
chevy s-10                         2720.0       1

In [58]:
Auto_re.loc[lambda df: (df['displacement'] < 300) & (df.index.str.contains('ford') | df.index.str.contains('datsun')),
                        ['weight', 'origin']]

weight  origin
name                                 
ford maverick          2587.0       1
datsun pl510           2130.0       3
datsun pl510           2130.0       3
ford torino 500        3302.0       1
ford mustang           3139.0       1
datsun 1200            1613.0       3
ford pinto runabout    2226.0       1
ford pinto (sw)        2395.0       1
datsun 510 (sw)        2288.0       3
ford maverick          3021.0       1
datsun 610             2379.0       3
ford pinto             2310.0       1
datsun b210            1950.0       3
ford pinto             2451.0       1
datsun 710             2003.0       3
ford maverick          3158.0       1
ford pinto             2639.0       1
datsun 710             2545.0       3
ford pinto             2984.0       1
ford maverick          3012.0       1
ford granada ghia      3574.0       1
datsun b-210           1990.0       3
ford pinto             2565.0       1
datsun f-10 hatchback  1945.0       3
ford granada           3525.0       1
ford mustang ii 2+2    2755.0       1
datsun 810             2815.0       3
ford fiesta            1800.0       1
datsun b210 gx         2070.0       3
ford fairmont (auto)   2965.0       1
ford fairmont (man)    2720.0       1
datsun 510             2300.0       3
datsun 200-sx          2405.0       3
ford fairmont 4        2890.0       1
datsun 210             2020.0       3
datsun 310             2019.0       3
ford fairmont          2870.0       1
datsun 510 hatchback   2434.0       3
datsun 210             2110.0       3
datsun 280-zx          2910.0       3
datsun 210 mpg         1975.0       3
ford escort 4w         2045.0       1
ford escort 2h         2380.0       1
datsun 200sx           2615.0       3
datsun 810 maxima      2930.0       3
ford granada gl        3060.0       1
ford fairmont futura   2865.0       1
datsun 310 gx          1995.0       3
ford granada l         2835.0       1
ford mustang gl        2790.0       1
ford ranger            2625.0       1