## Ch2 Basic Commands


Like most programming languages, Python uses functions to perform operations. *fun(input1,input2)*:

*fun*: function

*input1*,*input2*: inputs or arguments



In [1]:
print('fit a model with', 11, 'variables')

fit a model with 11 variables


In [2]:
?print # 查詢 function 用法

Object `print # 查詢 function 用法` not found.


In [3]:
3 + 5

8

In [4]:
"hello" + " " + "world"

'hello world'

The three most important types of sequences: lists, tuples, and 
strings

以下的 $x$ 為 list.

In [5]:
x = [3, 4, 5]
x

[3, 4, 5]

In [6]:
y = [4, 9, 7]
x + y

[3, 4, 5, 4, 9, 7]

list 裡面可以放任數字、文字等不同種類的 objects。當 x + y 時就只是把 list 內容做疊加。

### 2.3.3 Introduction to Numerical Python

*numpy*: library, or package

np.array(): function, 此function 在 numpy 裡

In [7]:
import numpy as np

In [8]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])
x+y

array([ 7, 13, 12])

In [9]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [10]:
x.ndim # x 陣列(array) 的維度

2

In [11]:
x.dtype # x 陣列內是整數 (int)

dtype('int32')

In [12]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [13]:
#np.array?

In [14]:
np.array([[1, 2], [3, 4]], float).dtype

dtype('float64')

In [15]:
x.shape #array 大小

(2, 2)

In [16]:
x = np.array([1, 2, 3, 4])
x.sum()

10

In [17]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

A method is a function that is associated with an object.

*sum()*: method for arrays

In [18]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3)) #指定 array 的大小為 (2,3), (2,3): tuple
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [19]:
x_reshape[0, 0] # python 的 indexing 是從 0 開始

1

In [20]:
x_reshape[1, 2]

6

In [21]:
print('x before we modify x_reshape:\n', x)
print('x_reshape before we modify x_reshape:\n', x_reshape)
x_reshape[0, 0] = 5
print('x_reshape after we modify its top left element:\n',
x_reshape)
print('x after we modify top left element of x_reshape:\n', x)

x before we modify x_reshape:
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


變更 x_reshape 的內容, x 的內容會一起改變:

tuple 的元素值不可以修改，也不可以刪除。

In [22]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

In [23]:
x_reshape.shape , x_reshape.ndim , x_reshape.T #T: 矩陣轉置(transpose)

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [24]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [25]:
x**2

array([25,  4,  9, 16, 25, 36], dtype=int32)

In [26]:
x**0.5

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

*np.random.normal()*: 生成常態分配隨機樣本 (vector)

In [27]:
#np.random.normal?
x = np.random.normal(size=50)
x

array([-0.00543974, -1.22701087, -0.11634913,  0.13155274, -0.54260377,
       -0.00541627,  0.51747349,  0.81865119,  1.37458952, -0.21448698,
        0.87810006, -0.25575754, -1.78243503,  0.57988684,  0.64793816,
       -0.27912516, -0.10637501,  0.6473766 , -0.26845011,  1.26847919,
       -1.71041692, -0.51704351,  1.78591819, -0.02062943, -0.00307936,
       -1.49555329,  1.23731935,  1.33003453, -1.68260325,  2.31789078,
        0.22079605,  0.42447057, -0.49701371, -1.02483234, -1.9724194 ,
        0.3838478 ,  0.2198846 ,  0.88346799,  0.4416866 , -1.20855638,
       -0.10266234,  0.29342336, -1.26665111, -0.30061413,  0.49257255,
       -0.59938876,  0.70049738, -1.08786545, -0.93705054,  0.50956231])

In [28]:
y = x + np.random.normal(loc=50, scale=1, size=50)

In [29]:
np.corrcoef(x, y) # 計算 x,y 的相關係數 (Pearson correlation coefficients)

array([[1.        , 0.75851923],
       [0.75851923, 1.        ]])

In [30]:
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2)) # 每次生成出的樣本不同

[ 0.7018435  -1.73740097]
[-7.32475751  4.67928083]


In [31]:
#設定 random seed，相同的 seed 下，生成的樣本相同。 np.random.default_rng()
rng = np.random.default_rng (1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng (1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [32]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10) #標準常態分配隨機樣本，樣本數 10
np.mean(y), y.mean() #樣本平均

(-0.1126795190952861, -0.1126795190952861)

In [33]:
np.var(y), y.var(), np.mean((y - y.mean())**2) #樣本變異數

(2.7243406406465125, 2.7243406406465125, 2.7243406406465125)

In [34]:
np.sqrt(np.var(y)), np.std(y) #樣本標準差

(1.6505576756498128, 1.6505576756498128)

In [35]:
X = rng.standard_normal((10, 3)) #常態隨機樣本，array 大小 (10,3)
X

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])

In [36]:
X.mean(axis=0) # 固定 column, 把 raw 取平均, 因此為長度 3 的向量 (共 3 個 column, 故做 3 次 mean)

array([ 0.15030588,  0.14030961, -0.34238602])

In [37]:
X.mean(0)

array([ 0.15030588,  0.14030961, -0.34238602])