## Cross validation 資料分群: 使用 sklearn 套件的 KFold 函數

參考網址: https://zhuanlan.zhihu.com/p/250253050

In [1]:
import numpy as np
from sklearn.model_selection import KFold

X = np.random.randint(1,100,20).reshape((10,2))
X


array([[21, 60],
       [40, 90],
       [46, 17],
       [98,  9],
       [48,  4],
       [22, 30],
       [17, 69],
       [74, 81],
       [45,  6],
       [96, 66]])

In [2]:
kf = KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [3]:
for X_train,X_test in kf.split(X):
    print(X_train,X_test)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [4]:
for X_train_i,X_test_i in kf.split(X):
    print(X[X_train_i],X[X_test_i])

[[46 17]
 [98  9]
 [48  4]
 [22 30]
 [17 69]
 [74 81]
 [45  6]
 [96 66]] [[21 60]
 [40 90]]
[[21 60]
 [40 90]
 [48  4]
 [22 30]
 [17 69]
 [74 81]
 [45  6]
 [96 66]] [[46 17]
 [98  9]]
[[21 60]
 [40 90]
 [46 17]
 [98  9]
 [17 69]
 [74 81]
 [45  6]
 [96 66]] [[48  4]
 [22 30]]
[[21 60]
 [40 90]
 [46 17]
 [98  9]
 [48  4]
 [22 30]
 [45  6]
 [96 66]] [[17 69]
 [74 81]]
[[21 60]
 [40 90]
 [46 17]
 [98  9]
 [48  4]
 [22 30]
 [17 69]
 [74 81]] [[45  6]
 [96 66]]
